# Generated by Django 5.0.6 on 2026-01-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationstatus",
            name="api_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="integrationstatus",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="integrationstatus",
            name="last_logs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="integrationstatus",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="integrationstatus",
            name="timeout",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="integrationstatus",
            name="verify_tls",
            field=models.BooleanField(default=True),
        ),
    ]
